title: Mindful Space
description: Legal Documents & Policies

# Site URL for GitHub Pages
url: "https://c0dedbear.github.io"
baseurl: "/mindful-track-public"

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
